[package]
name = "nfswalkdir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnfs = "0.1.1"
nix = "0.26.2"
crossbeam-channel = "0.5"
clap = "4.3"
